# Generated by Django 5.1.3 on 2024-11-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id_candidato', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apertura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('id_vacante', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Aplicacion.candidatos')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Aplicacion.puestos')),
            ],
        ),
        migrations.CreateModel(
            name='Resueltas',
            fields=[
                ('id_respuesta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('fecha_respuesta', models.DateField()),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Aplicacion.candidatos')),
                ('id_vacante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Aplicacion.vacantes')),
            ],
        ),
    ]
